# Fly.io deployment configuration for email validator API

app = "email-validator-api"
primary_region = "dfw"  # Dallas - central US location
fly_region_list = ["dfw", "fra"]
kill_signal = "SIGTERM"
kill_timeout = "30s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "bluegreen"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 10

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"
    protocol = "http"

[http_service.concurrency]
  type = "requests"
  hard_limit = 1000
  soft_limit = 800

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[env]
  EMAIL_API_SERVER_HOST = "0.0.0.0"
  EMAIL_API_SERVER_PORT = "3000"
  EMAIL_API_JSON_LOGS = "true"
  EMAIL_API_LOG_LEVEL = "info"
  EMAIL_API_ENABLE_SMTP_PROBE = "true"
  EMAIL_API_ENABLE_DMARC_ANALYSIS = "true"
  EMAIL_API_DNS_TIMEOUT_MS = "500"
  EMAIL_API_DNS_CACHE_SIZE = "10000"

# Metrics and monitoring
[metrics]
  port = 9091
  path = "/metrics"

# Secrets (set via flyctl secrets set)
# FLY_API_TOKEN - for deployment
# EMAIL_API_PRIVACY_SALT - for data hashing
# EMAIL_API_OTLP_ENDPOINT - for observability (optional)
# JWT_SECRET - JWT signing secret for developer authentication
# JWT_DEV_USERNAME - Developer username for JWT authentication
# JWT_DEV_PASSWORD - Developer password for JWT authentication